version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "3001:3000"
    env_file:
      - ./server/.env
    networks:
      - app-network
    environment:
      NODE_ENV: development
      # LA DB_URL PARA EL ENTORNO LOCAL APUNTANDO AL CONTENEDOR 'db'
      DB_URL: postgres://formulario_db_761p_user:7qwzOXSm7AKCIXs8zecyHfVCHgYFZNiL@db:5432/formulario_db_761p # <--- CAMBIADO AQUÍ
    restart: unless-stopped
    depends_on:
      - db

  db: # Servicio para PostgreSQL (solo para desarrollo local)
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: formulario_db_761p_user # <--- CAMBIADO AQUÍ
      POSTGRES_PASSWORD: 7qwzOXSm7AKCIXs8zecyHfVCHgYFZNiL # <--- CAMBIADO AQUÍ
      POSTGRES_DB: formulario_db_761p # <--- CAMBIADO AQUÍ
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge