version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "3001:3000"
    env_file:
      - ./server/.env
    networks:
      - app-network
    environment:
      NODE_ENV: development
      # Si tuvieras una DB_URL, la definirías aquí o en el .env del server
      # DB_URL: ${DB_URL}
    restart: unless-stopped

networks:
  app-network:
    driver: bridge